---
title: "HW9_XU"
author: "Shuangshuang Xu"
date: "11/23/2019"
output: pdf_document
---

```{r}
#install.packages("devtools")
library(devtools)
#devtools::install_github("rstudio/keras")
library(keras)
install_keras()
mnist<-dataset_mnist()
x_train<-mnist$train$x
y_train<-mnist$train$y
x_test<-mnist$test$x
y_test<-mnist$test$y
x_train<-array_reshape(x_train,c(nrow(x_train),784))
x_test<-array_reshape(x_test,c(nrow(x_test),784))
x_train<-x_train/255
x_test<-x_test/255
y_train<-to_categorical(y_train,10)
y_test<-to_categorical(y_test,10)
model<-keras_model_sequential()
model%>%
  layer_dense(units=256,activation="relu",input_shap=c(784))%>%
  layer_dropout(rate=0.4)%>%
  layer_dense(units=128,activation="relu")%>%
  layer_dropout(rate=0.3)%>%
  layer_dense(units=10,activation="softmax")
summary(model)
model%>%compile(
  loss="categorical_crossentropy",
  optimizer=optimizer_rmsprop(),
  metrics=c("accuracy")
)
  history<-model%>%fit(
    x_train,y_train,
    epochs=30,batch_size=128,
    validation_split=0.2
  )
plot(history)
model %>% evaluate(x_test, y_test)
model %>% predict_classes(x_test)
```

```{r}
fashion_mnist <- dataset_fashion_mnist()
c(train_images, train_labels) %<-% fashion_mnist$train
c(test_images, test_labels) %<-% fashion_mnist$test
class_names = c('T-shirt/top',
                'Trouser',
                'Pullover',
                'Dress',
                'Coat', 
                'Sandal',
                'Shirt',
                'Sneaker',
                'Bag',
                'Ankle boot')
dim(train_images)
dim(train_labels)
library(tidyr)
library(ggplot2)
image_1 <- as.data.frame(train_images[1, , ])
colnames(image_1) <- seq_len(ncol(image_1))
image_1$y <- seq_len(nrow(image_1))
image_1 <- gather(image_1, "x", "value", -y)
image_1$x <- as.integer(image_1$x)
ggplot(image_1, aes(x = x, y = y, fill = value)) +
  geom_tile() +
  scale_fill_gradient(low = "white", high = "black", na.value = NA) +
  scale_y_reverse() +
  theme_minimal() +
  theme(panel.grid = element_blank())   +
  theme(aspect.ratio = 1) +
  xlab("") +
  ylab("")
train_images <- train_images / 255
test_images <- test_images / 255
par(mfcol=c(5,5))
par(mar=c(0, 0, 1.5, 0), xaxs='i', yaxs='i')
for (i in 1:25) { 
  img <- train_images[i, , ]
  img <- t(apply(img, 2, rev)) 
  image(1:28, 1:28, img, col = gray((0:255)/255), xaxt = 'n', yaxt = 'n',
        main = paste(class_names[train_labels[i] + 1]))
}
model <- keras_model_sequential()
model %>%
  layer_flatten(input_shape = c(28, 28)) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dense(units = 10, activation = 'softmax')
model %>% compile(
  optimizer = 'adam', 
  loss = 'sparse_categorical_crossentropy',
  metrics = c('accuracy')
)
model %>% fit(train_images, train_labels, epochs = 5)
score <- model %>% evaluate(test_images, test_labels)
cat('Test loss:', score$loss, "\n")
cat('Test accuracy:', score$acc, "\n")
predictions <- model %>% predict(test_images)
```



